//go:build !ignore_autogenerated

// Hand-written deepcopy implementations (equivalent to controller-gen output).
// Regenerate with `make generate` once controller-gen is available.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *DezhanVault) DeepCopyInto(out *DezhanVault) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *DezhanVault) DeepCopy() *DezhanVault {
	if in == nil {
		return nil
	}
	out := new(DezhanVault)
	in.DeepCopyInto(out)
	return out
}

func (in *DezhanVault) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DezhanVaultList) DeepCopyInto(out *DezhanVaultList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		l := make([]DezhanVault, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&l[i])
		}
		out.Items = l
	}
}

func (in *DezhanVaultList) DeepCopy() *DezhanVaultList {
	if in == nil {
		return nil
	}
	out := new(DezhanVaultList)
	in.DeepCopyInto(out)
	return out
}

func (in *DezhanVaultList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DezhanVaultSpec) DeepCopyInto(out *DezhanVaultSpec) {
	*out = *in
	out.Storage = in.Storage.DeepCopy()
	if in.StorageClassName != nil {
		s := *in.StorageClassName
		out.StorageClassName = &s
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

func (in *DezhanVaultSpec) DeepCopy() *DezhanVaultSpec {
	if in == nil {
		return nil
	}
	out := new(DezhanVaultSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *DezhanVaultStatus) DeepCopyInto(out *DezhanVaultStatus) {
	*out = *in
	if in.Conditions != nil {
		l := make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&l[i])
		}
		out.Conditions = l
	}
}

func (in *DezhanVaultStatus) DeepCopy() *DezhanVaultStatus {
	if in == nil {
		return nil
	}
	out := new(DezhanVaultStatus)
	in.DeepCopyInto(out)
	return out
}
