apiVersion: v2
name: dezhan
description: Immutable, air-gapped, S3-compatible backup vault operator
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://obsernetics.github.io/dezhan/
sources:
  - https://github.com/obsernetics/dezhan
keywords:
  - backup
  - s3
  - worm
  - immutability
  - air-gap
