#!/bin/sh
# Generate deploy/dezhan.yaml: one file that installs the whole operator
# (namespace, CRD, RBAC, deployment) so users can run a single
#   kubectl apply -f https://raw.githubusercontent.com/obsernetics/dezhan/main/deploy/dezhan.yaml
# Keep this in sync by re-running after editing operator/config/*.
set -eu
HERE=$(cd "$(dirname "$0")/.." && pwd)
cd "$HERE"
mkdir -p deploy
OUT=deploy/dezhan.yaml

{
  echo "# Generated by scripts/gen-deploy.sh -- do not edit by hand."
  echo "# Installs the dezhan operator: namespace, CRD, RBAC, and deployment."
  echo "# After applying, create a DezhanVault (see operator/config/samples)."
  echo "apiVersion: v1"
  echo "kind: Namespace"
  echo "metadata:"
  echo "  name: dezhan-system"
  echo "  labels:"
  echo "    app.kubernetes.io/name: dezhan-operator"
  echo "---"
  cat operator/config/crd/dezhan.obsernetics.io_dezhanvaults.yaml
  echo "---"
  cat operator/config/rbac/rbac.yaml
  echo "---"
  # Everything after the Namespace doc (operator PDB + Deployment); the
  # Namespace is emitted above.
  awk 'f{print} /^---/{f=1}' operator/config/manager/manager.yaml
} > "$OUT"

echo "wrote $OUT ($(grep -c '^kind:' "$OUT") resources)"
